import React from 'react';
import { Shield, FileText } from 'lucide-react';

const Terms: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4 animate-fade-in">
      <div className="text-center mb-12">
        <div className="inline-flex p-4 bg-gray-100 rounded-2xl mb-6 text-gray-900">
           <FileText size={32} />
        </div>
        <h1 className="text-4xl font-bold text-gray-900 mb-4">Terms of Service</h1>
        <p className="text-gray-500">Last updated: October 26, 2023</p>
      </div>

      <div className="prose prose-lg max-w-none text-gray-600 space-y-8 bg-white p-8 md:p-12 rounded-3xl shadow-xl shadow-gray-100 border border-gray-100">
        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Introduction</h2>
          <p>
            Welcome to DataFlow AI. By accessing or using our website and services, you agree to be bound by these Terms of Service and our Privacy Policy. If you disagree with any part of these terms, you may not access the service.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Use of Services</h2>
          <p>
            DataFlow AI provides automated machine learning tools. You are responsible for:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4">
             <li>Maintaining the confidentiality of your account credentials.</li>
             <li>The accuracy and legality of the datasets you upload.</li>
             <li>Ensuring you have the right to use the data you upload for processing.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-4">3. AI & Data Processing</h2>
          <p>
            Our service uses Google Gemini and other AI technologies to process your data. While we strive for high accuracy, machine learning models are probabilistic and may produce errors. DataFlow AI does not guarantee 100% accuracy in predictions or insights.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Intellectual Property</h2>
          <p>
            The models generated by your data belong to you. However, the underlying technology, algorithms, and interface of DataFlow AI remain the exclusive property of DataFlow AI.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Termination</h2>
          <p>
            We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
          </p>
        </section>
      </div>
    </div>
  );
};

export default Terms;